baseURL: "https://sycther.github.io/garfield-blog"
languageCode: 'en'
title: 'Garfield: The Musical'
theme: "PaperModX"
description: "A Musical Interpretation of the Classic Garfield Comics"

params:
  disableThemeToggle: true
  defaultTheme: auto
  showtoc: true
  tocopen: true
  tocside: right
  ShowPostNavLinks: true
  article:
    showDate: false
    showReadingTime: false

  ShowFullTextinRSS: false

  homeInfoParams:
    Title: "Garfield: Manic Monday" 
    Content: |
      ## Summary
      ---
      This musical is a new imagination of the old beloved comics strips. 
      With Jon out of the house, Garfield wakes up to a nice peaceful morning... then Odie shows up. He decides to cheer himself up with a big o' bowl of lasagna. But his plans go arwy very quickly. 
      
      ## Premise
      > "The Garfield musical started out as a febel attempt to make a quick buck. 
      But we quickly realized that we can really capture the essence of Garfield's internal struggle to never truly express himself to his loved ones. 
      Not Only can we give him a chance to show how selfish he can be, but realize the importance of the friends and how to they can help you in the end."